services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    volumes:
      - ./db:/data
      - .:/app

  db:
    build:
      context: .
      dockerfile: Dockerfile.sqlite
    volumes:
      - ./db:/data
